### PR TITLE
Setup travis

### LINKED ISSUE #5: add CI and build

### PR DESCRIPTION
**Pull request by yohanboniface**
fix #5

### CODE REVIEW

**Comment by vincentsarago** [comment]
excellent, I had already started something over https://github.com/vincentsarago/python-vtzero/pull/2 but 👍 with travis 😄

**Comment by yohanboniface** [comment]
> excellent, I had already started something over vincentsarago#2 but +1 with travis smile

Strange! Why I don't see the PR here?

**Comment by vincentsarago** [comment]
my fault, because I wanted to wait for the polygon branch to get merged... I'm sorry about that

**Comment by yohanboniface** [comment]
OK, I see, those are PRs from your fork TO your fork :p

**Comment by vincentsarago** [comment]
I can bring it over here, butI'm fine with travis.

**Comment by yohanboniface** [comment]
OK, let's go with travis for now :)

**Pull request merged**
